"""Removed password column and added __password in users table

Revision ID: 6edd4184831c
Revises: 63b47727c487
Create Date: 2025-06-23 15:42:20.083340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6edd4184831c'
down_revision = '63b47727c487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_User__password', sa.String(), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_column('_User__password')

    # ### end Alembic commands ###
